ボウリングのスコア計算プログラムオブジェクト指向版の作成
misonog/ruby-practices pull request #6
Opened 2021-09-18 11:33 UTC by misonog

[ボウリングのスコア計算プログラムオブジェクト指向版](https://bootcamp.fjord.jp/practices/215) の課題提出用 Pull Request を作成しました。

お手数ですが、レビューをお願いいたします。

## 実行結果

```ruby
$ ./07.bowling_object/main.rb 6,3,9,0,0,3,8,2,7,3,X,9,1,8,0,X,6,4,5
139

$ ./07.bowling_object/main.rb 6,3,9,0,0,3,8,2,7,3,X,9,1,8,0,X,X,X,X
164

$ ./07.bowling_object/main.rb 0,10,1,5,0,0,0,0,X,X,X,5,1,8,1,0,4
107

$ ./07.bowling_object/main.rb 6,3,9,0,0,3,8,2,7,3,X,9,1,8,0,X,X,0,0
134

$ ./07.bowling_object/main.rb X,X,X,X,X,X,X,X,X,X,X,X
300
```

### スクリーンショット

![image](https://user-images.githubusercontent.com/24557514/133887179-d9d301cf-4a1b-416a-9228-f1e0301261eb.png)

## RuboCop

![RuboCop](https://user-images.githubusercontent.com/24557514/133887151-487a9973-bfdd-4e2f-804a-8088fa996488.png)

## メモ

- `Game` > `Frame` > `Shot` の順に下位のクラスは上位のクラスの情報を取得しないという方針で作成してみました
  - そのため、`Game` クラスでストライクとスペアのスコア計算を行っています（`Frame` クラスでは、自身のフレーム情報以外を知りえないので計算できない）
- `STRIKE_MARK = 'X'` というコードが 3 回出現しているので重複を防ぎたいのですが、module にするのがいいのか？などと悩んでしまい、今の状態になっています
  - `X` というマークが変わることはない気もするので定数である必要がそもそもないかも？とも思っています

2021-09-24 01:30 UTC, u1tnk requested changes
クラス構成は良いですね 👍 

全体的な方針なのですが、
「入力文字列を分解したデータを持っておいて、必要になったらインスタンスを作る」
という方針で実装されていそうですが、
「まず、入力データから適切なインスタンスを作っておく」
方が柔軟性が高く、見やすいコードになります。
GameオブジェクトがFrameオブジェクトの配列を持っていて、FrameオブジェクトはShotオブジェクトの配列を持っているという形にしてしまう感じです。
やってみてください 💪

2021-09-24 01:30 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +  STRIKE_MARK = 'X'
STRIKE_MARK を定数にするのは良いと思います。
ただ、全クラスにSTRIKE_MARKが定義されているのは良くないですね。
Shotだけで良いと思いますので、工夫してみてください。

2021-09-24 01:30 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @frame = frame
frameとありますが、中身は frame用の複数のmarkだと思います。変数名は中身に対応したものにしましょう。
また、配列が入っている変数は複数形にするのがruby界隈での慣習ですので複数形にしましょう。

2021-09-25 02:54 UTC, misonog commented on 07.bowling_object/lib/frame.rb
> +  STRIKE_MARK = 'X'
@u1tnk 
基本的には、`Shot`クラスのみで利用するようにしつつ、どうしても必要な箇所のみ`Shot::STRIKE_MARK` として、定数を参照するような形で対応いたしました！

2021-09-25 02:55 UTC, misonog commented on 07.bowling_object/lib/frame.rb
> +    @frame = frame
@u1tnk 
仰る通りですね。実態に合わせて`shots`に修正いたしました。

2021-09-25 13:26 UTC, u1tnk requested changes
良くなりましたね 👍 

結構コメントしてるのですが、名前と内容が乖離しているところ以外はもうちょっと良くなるなーと思って書いてしまったというレベルで対応必須ではありませんので、参考まで。

2021-09-25 13:26 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @shots = frame.map { |mark| Shot.new(mark) }
markが入ってる配列なら引数名も marksであった方が分かりやすいですね。

2021-09-25 13:26 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    frame = []
frameとう変数名だと frameインスタンスが入っていると思います。
marksだと重複してしまいますので 「引数の、全てが入っているmarks」と「今のフレームのmarks」を区別が付くように xxx_marksなどprefixを付けると良いと思います。

2021-09-25 13:26 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @shots[0].score == Shot::MAX_SCORE
これは `Shot::MAX_SCORE` とShot内の定数を参照するよりも、 `@shots.strike?`とした方が良いですね。
ShotクラスがStrikeの判定方法が分かるので、Shotクラスに聞いてあげるという感じです。

2021-09-25 13:26 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    !strike? && @score == Shot::MAX_SCORE
これはまあそのままでも良い気がしますが、
(結構細かいので対応しなくても良いレベルです)
細かい事を言うと 1つのShotの最高スコアと1フレームの最大スコアは違うのでFrameで定義しても良いとは思います。
更に細かい事を言うと、Frameで「スコア」というと「そのフレームのスコア」と「そのフレームで倒した数」のどちらかがはっきり分からないので見わけられる名前にするとより良いです。

2021-09-25 13:26 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +    last_frame_idx = @frames.size - 1
最終フレームのindexに名前をつけてるのは分かりやすくて良いですね 👍

2021-09-25 13:26 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    @shots[0, num].sum(&:score)
`sum(&:score)`とか使いこなしてるの良いですね 👍

2021-09-25 13:26 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +      if frame.strike? && idx != last_frame_idx
必須というほどでは無いですが、frame作るときにに indexを渡して `frame.last?` とできると見やすくなりますね。

2021-09-27 12:23 UTC, misonog commented on 07.bowling_object/lib/frame.rb
> +    @shots = frame.map { |mark| Shot.new(mark) }
@u1tnk 
引数名を`makrs`に修正いたしました！

2021-09-27 12:24 UTC, misonog commented on 07.bowling_object/lib/game.rb
> +    frame = []
@u1tnk 
仰る通りですね。`current_frame` という変数名に変更してみました。

2021-09-27 12:26 UTC, misonog commented on 07.bowling_object/lib/frame.rb
> +    @shots[0].score == Shot::MAX_SCORE
@u1tnk 
`Shot#strike?` メソッドを追加して修正してみました。
（`@shots.strike?` とはできませんでしたが…）

2021-09-27 12:31 UTC, misonog commented on 07.bowling_object/lib/frame.rb
> +    !strike? && @score == Shot::MAX_SCORE
@u1tnk 
仰る通りですね。。。ボウリングの理解が不足していました。
Frameクラスの`@score` インスタンス変数の名称を `@num_of_knocked_down_pins` に変更してみました。
これでそのフレームで倒したピンの数であることが表現できたかな？と思います。

（今回は必要ないので作成していませんが、Frameクラスにも`@score`は合ったほうがいいかもなとは思いました。各フレームのスコアを表示する機能を追加する場合なども考えると）

2021-09-27 12:35 UTC, misonog commented on 07.bowling_object/lib/game.rb
> +      if frame.strike? && idx != last_frame_idx
@u1tnk 
`Frame#last?` を追加しました。
まだ残ってしまっていますが、全体的にindexを利用する回数を減らして見やすくなるようにしてみています。

2021-09-27 14:19 UTC, u1tnk approved these changes
十分ですね 👍 
一点指摘した名前だけ修正してもらえれば問題無いのでApproveです 🙆‍♀️

2021-09-27 14:19 UTC, u1tnk commented on 07.bowling_object/lib/game.rb
> +      current_frame << mark
こうするなら、ここな `current_frame_marks`が良いと思います。

2021-09-27 14:56 UTC, misonog commented on 07.bowling_object/lib/game.rb
> +      current_frame << mark
@u1tnk 
確認ありがとうございます。
こちら改めて修正いたしましたので確認お願いいたします。

2021-09-28 22:46 UTC, merged